version: "3"
services:
  build: &build
    image: mpppk/gored
    volumes:
      - $PWD:/go/src/github.com/mpppk/go-scrapbox
    environment:
      GITHUB_TOKEN: $GITHUB_TOKEN
    working_dir: /go/src/github.com/mpppk/go-scrapbox
    command: make build -f Makefile
  lint:
    <<: *build
    command: make lint -f Makefile
  test:
    <<: *build
    command: make test -f Makefile
